### ISSUE TITLE
Input Validation for Amount:

### ISSUE THREAD

**Issue by Mehnaz2004** [CSI-DMCE-2024/QuickCart-Hacktoberfest2024#1]
Currently, the code assumes the amount input is always a valid integer. Implement input validation to ensure that users cannot enter negative numbers, non-integer values, or empty fields for the amount.

Suggestion: Use try-except blocks to catch invalid input and display an appropriate error message.

**Comment by jraviS2023** [comment]
Hey @Mehnaz2004, I'd love to tackle the input validation issue! Mind assigning it to me when you get a chance? Thanks!

**Comment by Loki2467** [comment]
Hello Maintainers, can I work on this?

**Comment by BhoomiSingh13** [comment]
Hello Maintainer , I want work on this issue , please assign me

**Comment by Mehnaz2004** [comment]
> Hello Maintainer , I want work on this issue , please assign me

Please Complete in the next 24 hours

**Comment by YashBawari18** [comment]
Hello maintainers, I would like to work on this issue, Kindly Assign me...

**Comment by TechMe103** [comment]
hey maintainers , i want to work on this issue

**Comment by Shreyash212-tech** [comment]
Hey Maintainers , Could you please assigned me this issue ...
