### ISSUE TITLE
Persistent Storage of Shopping List

### ISSUE THREAD

**Issue by Mehnaz2004** [CSI-DMCE-2024/QuickCart-Hacktoberfest2024#2]
The shopping list resets every time the application is closed. Implement functionality to save the shopping list to a file (e.g., JSON or CSV) and load it when the application starts.

Suggested Solution: Use the json module to read/write the shopping list data.

**Comment by MRELEC1R0N** [comment]
hey  i would like to take this task

**Comment by nupurnigudkar9404** [comment]
Hey maintainers. I want to work on this issue

**Comment by Mehnaz2004** [comment]
> Hey maintainers. I want to work on this issue

go for it

**Comment by MRELEC1R0N** [comment]
Thank you for the opportunity, will update you on it asap

**Comment by MRELEC1R0N** [comment]
@Mehnaz2004  i have already created a pr for this issue and been working on it today

**Comment by TechMe103** [comment]
hello maintainers i would like to work on this issue
