### ISSUE TITLE
Adding a category dropdown

### ISSUE THREAD

**Issue by maithili008** [CSI-DMCE-2024/QuickCart-Hacktoberfest2024#28]
Adding a category dropdown would allow users to categorize their items for better organization. They can select categories like grocery, electronics, household, etc. when adding an item.

I would like to tackle this task and request the maintainers to assign me this issue.

**Comment by DaD-ArgenTuM** [comment]
Hello Maintainers, I want to work on this issue.

**Comment by Mehnaz2004** [comment]
Go for it!!

> Hello Maintainers, I want to work on this issue.

**Comment by maithili008** [comment]
I request the maintainers to assign the issue to me as i have raised it first.
