### ISSUE TITLE
Edit Item Feature

### ISSUE THREAD

**Issue by Mehnaz2004** [CSI-DMCE-2024/QuickCart-Hacktoberfest2024#3]
Users should have the ability to edit the quantity of an existing item instead of just removing it. Implement an edit functionality that allows users to update the amount of an item.

Suggested Solution: Add an "Edit Item" button and create a corresponding function to modify the item’s amount.

**Comment by TechMe103** [comment]
hey i want to work on this issue..Assign to me

**Comment by mohitrajsinha** [comment]
Hey @Mehnaz2004 ,
I want to work on this issue. Assign it to me.

**Comment by BhoomiSingh13** [comment]
Hello Maintainer, i want to work on this issue

**Comment by Mehnaz2004** [comment]
> Hello Maintainer, i want to work on this issue

Please Complete this in the next 24 Hours
