### ISSUE TITLE
Improve UI: Update Color Scheme and Text Visibility

### ISSUE THREAD

**Issue by Mehnaz2004** [CSI-DMCE-2024/QuickCart-Hacktoberfest2024#36]
Please style the UI using the following color palette. Feel free to incorporate any additional styling features such as fonts or icons within this palette to enhance the overall design.
Pallete: #2d3250, #ffffff, #4e545f, #FF7F50, #B0B3C5, #A0A3B2

Ref image: 
![image](https://github.com/user-attachments/assets/c023119e-b1ce-4d65-99df-208b359860fd)

**Comment by Muskan2404** [comment]
Please assign me this

**Comment by Mehnaz2004** [comment]
Go for it and complete the same in the next 24 hours

> Please assign me this

**Comment by Muskan2404** [comment]
> Go for it and complete the same in the next 24 hours
> 
> > Please assign me this

Do you want the exact same design as the image or I can design it how I like with the same colour pallette?

**Comment by Mehnaz2004** [comment]
> > Go for it and complete the same in the next 24 hours
> > > Please assign me this
> 
> Do you want the exact same design as the image or I can design it how I like with the same colour pallette?

U can go for any style you want just try to keep it dark mode, you can change the colour pallete as well that was just given in case someone does not want to find one.

**Comment by Muskan2404** [comment]
Is this done?

**Comment by Junkie-source** [comment]
Hello Maintainers! I would like to work on this issue.

**Comment by Mehnaz2004** [comment]
> Is this done? why did you unassign me?

Please try to complete in the next 24 hours or i must reassign

**Comment by Muskan2404** [comment]
> > Is this done? why did you unassign me?
> 
> Please try to complete in the next 24 hours or i must reassign

I've completed it. Here's the link:
https://www.figma.com/design/zxvXciooompaoiD8WMQGGC/Shopping-List?node-id=0-1&t=YzdawQuaZQuG73Ho-1 
Tell me if you need any changes

**Comment by Mehnaz2004** [comment]
can you do this using just tkinter and python as i would like to keep the code as simple as possible, so please try to not change the UI too much as this is supposed to be a beginner friendly repo that many people can work on with minimal coding knowledge

**Comment by Muskan2404** [comment]
> Collaborator

Wasn't it supposed to be a design only or do i need to code as well?

**Comment by Mehnaz2004** [comment]
it is code implementation not just designing

**Comment by Muskan2404** [comment]
> it is code implementation not just designing

I misunderstood then please unassign me

**Comment by Mehnaz2004** [comment]
> > it is code implementation not just designing
> 
> I misunderstood then please unassign me

Okay thank you for trying.

**Comment by laksh-krishna-sharma** [comment]
Hi @Mehnaz2004 , May I work on this issue with a bit of your guidance.

**Comment by SanjanaSaw** [comment]
Hello Maintainers, i want to work on this issue

**Comment by Mehnaz2004** [comment]
> hey maintainer , can u assign me

go for it and see to it that u complete in the next 24 hours

**Comment by laksh-krishna-sharma** [comment]
@Mehnaz2004 , please review my PR #51

**Comment by Mehnaz2004** [comment]
> Hello Maintainers, i want to work on this issue 
Go for it!

**Comment by SanjanaSaw** [comment]
@Mehnaz2004   I have fixed the issue kindly check my PR
