### ISSUE TITLE
Clear List Functionality

### ISSUE THREAD

**Issue by Mehnaz2004** [CSI-DMCE-2024/QuickCart-Hacktoberfest2024#4]
Implement a feature that allows users to clear the entire shopping list with a single button.
Suggested Solution: Create a button labeled "Clear List" that removes all items from the shopping list and updates the display.

**Comment by bakayu** [comment]
Hey! I would like to implement this feature, please assign the issue to me. :)

**Comment by bakayu** [comment]
I have raised a PR [link](https://github.com/CSI-DMCE-2024/QuickCart-Hacktoberfest2024/pull/10) addressing the issue.
Your feedback is highly appreciated! Thanks.

**Comment by Khanvilkarshravani27** [comment]
Hello Maintainer , Can I work on this issue?

**Comment by Mehnaz2004** [comment]
> Hello Maintainer , Can I work on this issue?

Please complete this issue as soon as possible
