### ISSUE TITLE
#Fix the Json File saving path

### ISSUE THREAD

**Issue by Mehnaz2004** [CSI-DMCE-2024/QuickCart-Hacktoberfest2024#47]
While the data is being saved to json file properly, It is saving the data outside the project directory when it should be saving it inside the directory.

![image](https://github.com/user-attachments/assets/a375d91b-4382-47f5-95a1-3e22015250ff)

Fix this BUG of json saving path!

**Comment by suyashutekar11** [comment]
Hey can I help you?

**Comment by kaushikatgithub** [comment]
hey, i want to work on this issue, please assign me.

**Comment by Rupesh-Singh-Karki** [comment]
Hii @Mehnaz2004 , may i work on this issue.

**Comment by Thestoic3467** [comment]
Hii maintainer !! Would u pls assign me this task

**Comment by Yashj2004** [comment]
@Mehnaz2004  could you plz assign this issue to me

**Comment by amitmaurya19** [comment]
i have done this already , the json file will automatically be saved in the same directory as the main file ,, and if there is no json file ,, it will automatically create it .

 Please assign me this task @Mehnaz2004

**Comment by DaD-ArgenTuM** [comment]
Hello Maintainers! I would like to work on this issue.
