### ISSUE TITLE
User Interface Improvements

### ISSUE THREAD

**Issue by Mehnaz2004** [CSI-DMCE-2024/QuickCart-Hacktoberfest2024#5]
Enhance the user interface by adding colors, improving button sizes, and organizing layout for better user experience.
Suggested Solution: Use the tkinter styling options to modify widget appearances.

**Comment by bakayu** [comment]
Hey! I would like to implement this feature, please assign the issue to me. :)

**Comment by akadeepesh** [comment]
I'm on it, assign it to me please.

**Comment by tghosh294** [comment]
Hello Maintainer, I would like to work on this issue

**Comment by Mehnaz2004** [comment]
> Hello Maintainer, I would like to work on this issue

go for it

**Comment by TechMe103** [comment]
hey maintainers i want to work on this issue
