### ISSUE TITLE
Search Functionality

### ISSUE THREAD

**Issue by Mehnaz2004** [CSI-DMCE-2024/QuickCart-Hacktoberfest2024#6]
Implement a search feature that allows users to quickly find an item in the shopping list by typing the item name.
Suggested Solution: Create an entry field for search and filter the list displayed in the Listbox based on user input.

**Comment by TechMe103** [comment]
hey i would like to solve this issue...Assign to me this issue ?

**Comment by ReshmaZore** [comment]
Hey maintainer, I would like to work on this issue

**Comment by Mehnaz2004** [comment]
> Hey maintainer, I would like to work on this issue

Please Complete it in the next 24 hours

**Comment by aaliyahnl** [comment]
I began working on this before it was assigned, but wanted to submit a PR just in case it wasn't completed in time.
https://github.com/CSI-DMCE-2024/QuickCart-Hacktoberfest2024/pull/17

**Comment by YashBawari18** [comment]
Hello maintainers, I would like to work on this issue, Kindly Assign me...

**Comment by Chetansm684** [comment]
Hey @Mehnaz2004 , I would like to work on this issue.

**Comment by Mehnaz2004** [comment]
Issue Completed
