### ISSUE TITLE
Button Activation State

### ISSUE THREAD

**Issue by Mehnaz2004** [CSI-DMCE-2024/QuickCart-Hacktoberfest2024#7]
Buttons like "Remove Item" and "Calculate Total" should be disabled if there are no items in the shopping list, but they currently remain active.
Suggested Solution: Implement checks to enable or disable buttons based on the current state of the shopping list.

**Comment by TechMe103** [comment]
hey i would like to work upon this issue...Assign to me

**Comment by Mehnaz2004** [comment]
> hey i would like to work upon this issue...Assign to me

Please Complete this in the next 24 hours

**Comment by TechMe103** [comment]
hey maintainers , i would like to work on this issue

**Comment by Mehnaz2004** [comment]
> hey maintainers , i would like to work on this issue

go for it and complete in the next 24 hours

**Comment by YashBawari18** [comment]
Hello maintainers, I would like to work on this issue, Kindly Assign me...

**Comment by Mehnaz2004** [comment]
> hey i would like to work upon this issue...Assign to me

This is your last day to resolve your issues, please complete this issue with ss or else i will assign the issue to someone else by tonight 12 am.

**Comment by TechMe103** [comment]
Okay

**Comment by Mehnaz2004** [comment]
> Hello maintainers, I would like to work on this issue, Kindly Assign me...

Go for it and try to complete in the next 24 hours

**Comment by DaD-ArgenTuM** [comment]
Hello Maintainers. I would like to work on this issue.

**Comment by Mehnaz2004** [comment]
> Hello Maintainers. I would like to work on this issue.

go for it
