### ISSUE TITLE
Incorrect Total Calculation

### ISSUE THREAD

**Issue by Mehnaz2004** [CSI-DMCE-2024/QuickCart-Hacktoberfest2024#8]
The calculate_total function currently counts the number of unique items in the shopping list instead of calculating the total amount of all items. Users expect to see the total quantity of items they have added to the list, not just the count of distinct items.

Suggested Solution: Modify the calculate_total function to sum the amounts of all items in the shopping_list dictionary and display the total amount correctly.

**Comment by bakayu** [comment]
Hey! I would like to work on this :)
Please assign me the issue!

**Comment by bakayu** [comment]
Hey @Mehnaz2004 I just ran a test to check what was causing the problem and it seems like it is working as intended...

linking a screen shot:
![image](https://github.com/user-attachments/assets/9a627cc3-aa45-4b76-bca4-ebc1db0958d1)

**Comment by Loki2467** [comment]
Hey leads, can i work on this issue ?
