### ISSUE TITLE
Add Price Column for Each Item

### ISSUE THREAD

**Issue by Mehnaz2004** [CSI-DMCE-2024/QuickCart-Hacktoberfest2024#9]
Description:
The shopping list should display an additional column that specifies the price for each item in the list (e.g., "tomatoes $40"). This change allows users to easily see not only the items but also the amount of money they may need

**Comment by mohitrajsinha** [comment]
Hi @Mehnaz2004,
Please assign me this issue.

**Comment by TechMe103** [comment]
hey leads i want to work on this. Assign to me this

**Comment by Mehnaz2004** [comment]
> > hey leads i want to work on this. Assign to me this
> > please complete it asap
It's been 2 days please complete it as soon as possible

**Comment by TechMe103** [comment]
I have completed it

**Comment by Mehnaz2004** [comment]
This issue was completed by TechMe103
